# Generated by Django 4.2.6 on 2024-11-14 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='dateTime',
            new_name='date',
        ),
    ]
